# Generated by Django 5.1.15 on 2026-04-24 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=300)),
                ('busca_exata', models.BooleanField(default=True)),
                ('ano_inicio', models.PositiveIntegerField()),
                ('ano_fim', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('extraindo', 'Extraindo do IOMAT'), ('classificando', 'Classificando com IA'), ('concluido', 'Concluido'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('mensagem_erro', models.TextField(blank=True, default='')),
                ('total_extraidos', models.PositiveIntegerField(default=0)),
                ('total_relevantes', models.PositiveIntegerField(default=0)),
                ('total_duvidosos', models.PositiveIntegerField(default=0)),
                ('total_descartados', models.PositiveIntegerField(default=0)),
                ('total_erros', models.PositiveIntegerField(default=0)),
                ('total_reaproveitados', models.PositiveIntegerField(default=0)),
                ('custo_estimado_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buscas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Busca',
                'verbose_name_plural': 'Buscas',
                'ordering': ('-created_at',),
            },
        ),
    ]
