# Generated by Django 5.1.15 on 2026-04-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchjob',
            name='ano_atual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchjob',
            name='doc_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchjob',
            name='fase_atual',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='searchjob',
            name='mensagem_progresso',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
