# Generated by Django 5.1.15 on 2026-04-24 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_searchjob_ano_atual_searchjob_doc_atual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('codigo', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=80)),
                ('detalhe', models.CharField(blank=True, default='', max_length=160)),
                ('agente', models.CharField(choices=[('AI', 'IA'), ('HUM', 'Humano'), ('SYS', 'Sistema')], default='SYS', max_length=5)),
                ('estado', models.CharField(choices=[('queued', 'Na fila'), ('running', 'Em execucao'), ('done', 'Concluida'), ('failed', 'Falhou'), ('skipped', 'Pulada')], default='queued', max_length=10)),
                ('itens_total', models.PositiveIntegerField(default=0)),
                ('itens_feitos', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('mensagem', models.CharField(blank=True, default='', max_length=250)),
                ('search_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='searches.searchjob')),
            ],
            options={
                'verbose_name': 'Etapa da pipeline',
                'verbose_name_plural': 'Etapas da pipeline',
                'ordering': ('search_job', 'ordem'),
                'constraints': [models.UniqueConstraint(fields=('search_job', 'codigo'), name='uniq_stage_per_job')],
            },
        ),
    ]
