# Generated by Django 5.1.15 on 2026-06-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_pipelinestage'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchjob',
            name='forcar_reclassificacao',
            field=models.BooleanField(default=False),
        ),
    ]
