# Generated by Django 5.1.15 on 2026-06-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0004_searchjob_forcar_reclassificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchjob',
            name='usar_delimitador',
            field=models.BooleanField(default=False),
        ),
    ]
