# Generated by Django 5.1.15 on 2026-06-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0005_searchjob_usar_delimitador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchjob',
            name='usar_delimitador',
            field=models.BooleanField(default=True),
        ),
    ]
