# Generated by Django 5.1.15 on 2026-06-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0006_alter_searchjob_usar_delimitador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchjob',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('extraindo', 'Extraindo do IOMAT'), ('classificando', 'Classificando com IA'), ('pausado', 'Pausado'), ('concluido', 'Concluido'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
    ]
