# Generated by Django 5.1.15 on 2026-04-24 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao_id', models.CharField(db_index=True, max_length=64)),
                ('tipo_edicao', models.PositiveSmallIntegerField(default=1)),
                ('pagina', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField(db_index=True)),
                ('nome_edicao', models.CharField(blank=True, default='', max_length=200)),
                ('data_pub', models.CharField(blank=True, default='', max_length=32)),
                ('link_oficial', models.URLField(blank=True, default='', max_length=600)),
                ('texto_bruto', models.TextField(blank=True, default='')),
                ('caminho_pdf', models.CharField(blank=True, default='', max_length=500)),
                ('primeiro_visto_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-primeiro_visto_em',),
                'indexes': [models.Index(fields=['ano'], name='documents_d_ano_1ba909_idx'), models.Index(fields=['edicao_id'], name='documents_d_edicao__97750f_idx')],
                'unique_together': {('edicao_id', 'pagina')},
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_buscado', models.CharField(blank=True, default='', max_length=300)),
                ('classificacao', models.CharField(choices=[('relevante', 'Relevante'), ('duvidoso', 'Duvidoso'), ('irrelevante', 'Irrelevante')], db_index=True, max_length=16)),
                ('tipo_ato', models.CharField(blank=True, default='', max_length=120)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('prompt_enviado', models.TextField(blank=True, default='')),
                ('resposta_crua', models.TextField(blank=True, default='')),
                ('modelo_ia', models.CharField(blank=True, default='', max_length=64)),
                ('tokens_input', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_output', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classificacoes', to='searches.searchjob')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='documents.document')),
            ],
            options={
                'verbose_name': 'Classificacao IA',
                'verbose_name_plural': 'Classificacoes IA',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['classificacao'], name='documents_c_classif_b79050_idx')],
            },
        ),
    ]
