# Generated by Django 5.1.15 on 2026-05-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classificacao',
            field=models.CharField(choices=[('super_relevante', 'Super Relevante'), ('relevante', 'Relevante'), ('duvidoso', 'Duvidoso'), ('irrelevante', 'Irrelevante')], db_index=True, max_length=20),
        ),
    ]
