# Generated by Django 5.1.15 on 2026-06-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_super_relevante_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='com_contexto',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='classification',
            name='paginas_contexto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
