# Generated by Django 5.1.15 on 2026-06-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_classification_com_contexto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classificacao',
            field=models.CharField(choices=[('super_relevante', 'Super Relevante'), ('relevante', 'Relevante'), ('duvidoso', 'Duvidoso'), ('irrelevante', 'Irrelevante'), ('erro', 'Erro (formato)')], db_index=True, max_length=20),
        ),
    ]
