# Generated by Django 5.1.15 on 2026-05-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_super_relevante_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_amostra', models.PositiveIntegerField()),
                ('aproveitou_avaliados', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluida')], db_index=True, default='em_andamento', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BlindItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('categoria_ia', models.CharField(db_index=True, max_length=20)),
                ('tipo_ato_ia', models.CharField(blank=True, max_length=120)),
                ('justificativa_ia', models.TextField(blank=True)),
                ('decisao_humana', models.CharField(blank=True, choices=[('super_relevante', 'Super relevante'), ('aprovado', 'Aprovado'), ('ressalva', 'Aprovado com ressalva'), ('rejeitado', 'Rejeitado')], max_length=20, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('resultado_binario', models.CharField(blank=True, max_length=16)),
                ('concordancia', models.BooleanField(null=True)),
                ('tempo_avaliacao_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('fonte', models.CharField(choices=[('sorteado', 'Sorteado'), ('reaproveitado', 'Reaproveitado')], default='sorteado', max_length=16)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_items', to='documents.document')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='validations.blindsession')),
            ],
            options={
                'ordering': ('ordem',),
                'constraints': [models.UniqueConstraint(fields=('session', 'document'), name='uniq_blind_item_por_sessao')],
            },
        ),
    ]
