# Generated by Django 5.1.15 on 2026-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='modelo_selecionado',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openwebui_base_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('openwebui', 'OpenWebUI')], default='openai', max_length=20),
        ),
    ]
