# Generated by Django 5.1.15 on 2026-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_modelo_selecionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ver_respostas_brutas',
            field=models.BooleanField(default=False),
        ),
    ]
