# Generated by Django 5.1.15 on 2026-04-24 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, max_length=16)),
                ('comentario', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='documents.document')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisao',
                'verbose_name_plural': 'Revisoes',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('document',), name='uniq_review_por_documento')],
            },
        ),
    ]
