# Generated by Django 5.1.15 on 2026-05-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='decisao',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('ressalva', 'Aprovado com ressalva'), ('rejeitado', 'Rejeitado')], db_index=True, max_length=16),
        ),
    ]
