# Generated by Django 5.1.15 on 2026-05-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_add_ressalva_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='decisao',
            field=models.CharField(choices=[('super_relevante', 'Super relevante'), ('aprovado', 'Aprovado'), ('ressalva', 'Aprovado com ressalva'), ('rejeitado', 'Rejeitado')], db_index=True, max_length=20),
        ),
    ]
